name: OinkTrade
version: 1.0
api-version: 1.14
main: com.tek.otrade.Main

depend: [Vault, RedstoneCore]

commands:
  oinktrade:
    description: Main OinkTrade command
    aliases: [otrade, trade]